### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by dhilipsiva** [appknox/irene#130]
- [x] Each component should be in a `box` - tracking at #133
- [x] Freestyle live-styleguide not loading #131
- [ ] Freestyle lifeguide, make components #132
- [x] Fix the layout of the dashboard
- [x] Rearrange the items as discussed below ⬇️ 
- [x] Appknox Logo
- [x] Center Submit stuff
- [x] ~~Remove Breadcrumb~~ [Breadcrum is not removed and Logo is added on that as told by Manik]
- [x] Orginal Color on beta
- [x] Paste And / Win Store URL
- [x] Pretty Chart
- [x] Vuln count- color coded
- [x] iOS / And icon
- [x] no caps in package name and version
- [x] No All CAps
- [x] http://0.0.0.0:4200/file/2 - > chart and info nearer
- [x] No background on analysis detail
- [x] Pull Right -> lables
- [ ] write proper testcases
