### ISSUE TITLE
[EPIC] Upgrade Dashboard

### ISSUE THREAD

**Issue by subho007** [appknox/irene#554]
- [ ] Modularize each features in a different ember modules
- [ ] Rewrite styles for SASS
- [ ] Use external layout and extend
